WDDR101 IG FIFO Loop
waviousllc/wav-lpddr-sw pull request #122
Opened 2021-12-17 17:36 UTC by wavious-wpatty

Fixes:
  - None

Features:
  - Added support for IG FIFO loop feature specific to WDDR101 (#109)

2021-12-17 22:45 UTC, wavious-jbasista requested changes

2021-12-17 22:45 UTC, wavious-jbasista commented on target/wddr101/include/drivers/dfi/dfi_fifo_ext.h
> + *          timestmap. The pointers should store the timestamp values that
typo in timestamp.

2021-12-18 00:02 UTC, wavious-wpatty commented on target/wddr101/include/drivers/dfi/dfi_fifo_ext.h
> + *          timestmap. The pointers should store the timestamp values that
good catch.

2021-12-18 01:13 UTC, wavious-jbasista approved these changes

2021-12-20 22:47 UTC, merged