Table Reorganization
waviousllc/wav-lpddr-sw pull request #83
Opened 2021-09-22 21:47 UTC by wavious-wpatty

Fixes:
  - None

Features:
  - Combined calibration and configuration tables
  - Moved table includes to dedicated directory

2021-09-23 18:42 UTC, wavious-jbasista requested changes
Just some small comment changes

2021-09-23 18:42 UTC, wavious-jbasista commented on include/table/dfi/table.h
> + *          end of clock pulse o extend width by configured number of phases.
typo, add t in to

2021-09-23 18:42 UTC, wavious-jbasista commented on include/table/dfi/table.h
> + * @details DFI Traffic Override Traffic configuration. Configures dynamic clock
Two traffic in sentence, remove one

2021-09-23 18:42 UTC, wavious-jbasista commented on include/table/dfi/table.h
> + * wrd.cs   Write data chip select.
should we add .fields to these?

2021-09-23 18:42 UTC, wavious-jbasista commented on include/table/dfi/table.h
> + */
Missing description of members in struct.

2021-09-23 18:42 UTC, wavious-jbasista commented on include/table/dp/table.h
> +
extra line space

2021-09-23 18:42 UTC, wavious-jbasista commented on include/table/dram/table.h
> + * txsr             Self-Refresh Exit timing.
Move these to the top to match structure.

2021-09-23 18:42 UTC, wavious-jbasista commented on include/table/dram/table.h
> + * mr14    Mode Register 14 (DQ VREF).
alignment

2021-09-23 18:42 UTC, wavious-jbasista commented on include/table/driver/table.h
> + * mode     driver mode.
Organize to match structure

2021-09-23 18:42 UTC, wavious-jbasista commented on include/table/pi/tx_table.h
> + * @dfi     Configuration for DFI delay match Phase Interpolator.
Remove @

2021-09-23 18:42 UTC, wavious-jbasista commented on include/table/receiver/table.h
> +/**
add a space above

2021-09-23 20:37 UTC, wavious-wpatty commented on include/table/dfi/table.h
> + * wrd.cs   Write data chip select.
No, it's okay. It's implied. There's no other .cs, etc.

2021-09-23 20:37 UTC, wavious-wpatty commented on include/table/dfi/table.h
> + */
It's been like that. but I will add.

2021-09-27 13:43 UTC, wavious-jbasista approved these changes
Looks good

2021-09-27 16:04 UTC, merged